#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO

# Author: Sizov Sergey <sizovIT@gmail.com>

DESC="Factorio Game"
GAME_FOLDER=/etc/factorio
DAEMON=$GAME_FOLDER/factorio/bin/x64/factorio
PIDFILE=/var/run/factorio.pid

case "$1" in
    start)

	if [ -z $2 ]
	then
	    echo "You must set SAVE argument!"
	    exit 1
	fi

        echo "Starting $DESC"
	start-stop-daemon --start --exec $DAEMON -m --pidfile $PIDFILE --background -- --start-server $2
	;;
    stop)
	echo "Stopping $DESC"
        start-stop-daemon --stop --pidfile $PIDFILE --remove-pidfile
	;;
    *)
	echo "Usage: /etc/init.d/factorio {start SAVENAME|stop}"
	exit 1
	;;
esac

exit 0
